version: 2.1

defaults: &defaults
  working_directory: ~/repo_name
  docker:
    - image: circleci/node:11.15.0

jobs:
  deploy_production:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build
          command: npm run build
      - run:
          name: install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - run:
          name: deploy to Now
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token "${NOW_DEPLOY_TOKEN}" --local-config .now/now.production.json
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
                now --token "${NOW_DEPLOY_TOKEN}" --local-config .now/now.staging.json
            else
                now --token "${NOW_DEPLOY_TOKEN}" --local-config .now/now.json
            fi

workflows:
  version: 2.1
  deploy_web:
    jobs:
      - deploy_production:
          filters:
            branches:
              only: master
